title: Cemetery Data Management 
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: 127.0.0.1:4000

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


color_scheme: dark
# callouts_level: quiet # or loud
# callouts:
#   note:
#     title: Note
#     color: blue

