title: Cemetery Data Management
description: Port of the Cemetery Data Management Solution to QGIS.
#remote_theme: carlosperate/jekyll-theme-rtd
remote_theme: allejo/jekyll-docs-theme@v1.0.0

# Theme settings:
site_author: Steven Graham
#repo_url: "https://github.com/carlosperate/jekyll-theme-rtd"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
#hljs_style: github-gist
